### ISSUE TITLE
[ios] not a object  UMAnalyticsModule.onPageStart

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [umeng/React_Native_Compent#43]
友盟统计正常， 但是使用 `UMAnalyticsModule.onPageStart` 报错， Android也使用正常，请问这是为什么呢？

```javascript
import {NativeModules} from 'react-native';
const UMAnalyticsModule = NativeModules.UMAnalyticsModule;

UMAnalyticsModule.onPageStart('xxx');
```

```pod
  pod 'UMCCommon'
  pod 'UMCAnalytics'
  pod 'UMCSecurityPlugins'
```

```
#import <UMAnalytics/MobClick.h>
#import <UMCommon/UMConfigure.h>

[UMConfigure initWithAppkey:@"xxx" channel:@"xxx"];
[MobClick setScenarioType:E_UM_NORMAL];
```

**Comment by liran** [comment]
![image](https://user-images.githubusercontent.com/22112008/105717850-91efb300-5f5b-11eb-9571-c8899c0b1a8d.png)
#38 
因为Ios和Android桥接文件里函数名不统一导致的，需要手动修改其中一端的函数名，否则js调用时会找不到函数。

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> ![image](https://user-images.githubusercontent.com/22112008/105717850-91efb300-5f5b-11eb-9571-c8899c0b1a8d.png)
> #38
> 因为Ios和Android桥接文件里函数名不统一导致的，需要手动修改其中一端的函数名，否则js调用时会找不到函数。

十分感谢，你的回答可以解决
